<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log in as Alexmacdemaco0gmail.com  Not _cd0f21</name>
   <tag></tag>
   <elementGuidId>0682eba3-cd51-44fb-9aab-58f2e9bef87c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._4-u5._30ny</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4be332fa-b6e1-4935-a5b2-209eb158ac50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_4-u5 _30ny</value>
      <webElementGuid>0b2bc705-65b7-4ef1-b2e0-461b4e88dc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in as Alexmacdemaco0@gmail.com · Not you?The password that you've entered is incorrect. Forgotten password?Log inLog In with GoogleForgotten password?</value>
      <webElementGuid>fa8aab62-955d-4690-a66a-3a7c812903f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;_4-u5 _30ny&quot;]</value>
      <webElementGuid>677a3305-d1b9-4c6f-8e97-f570152a8255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div</value>
      <webElementGuid>70239421-2632-4f8a-8fd6-512e5e95cda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>2301c2da-5292-42fc-9b87-fa224c75a9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Log in as Alexmacdemaco0@gmail.com · Not you?The password that you&quot; , &quot;'&quot; , &quot;ve entered is incorrect. Forgotten password?Log inLog In with GoogleForgotten password?&quot;) or . = concat(&quot;Log in as Alexmacdemaco0@gmail.com · Not you?The password that you&quot; , &quot;'&quot; , &quot;ve entered is incorrect. Forgotten password?Log inLog In with GoogleForgotten password?&quot;))]</value>
      <webElementGuid>eb94ede0-e220-4ee2-917f-6b364388ae61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
