<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Custom_sex</name>
   <tag></tag>
   <elementGuidId>e6047f72-4a29-4ec7-8e1c-90049b16ed10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='u_0_6_BZ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_0_6_BZ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>088f1d88-6937-4421-bb0f-ccf481d17e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>faf7d408-f720-4022-9c51-2dac72cb04f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_8esa</value>
      <webElementGuid>d90ebfa0-3094-4127-8510-23e7816515f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sex</value>
      <webElementGuid>0bad4c3c-ed9d-4e7d-b3b9-1b2457e4438c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7ade5e06-79d5-491a-b2e1-43bd16559a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_6_BZ</value>
      <webElementGuid>eb2399b8-cb1d-4b1b-af57-ddb8d0b7855f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_6_BZ&quot;)</value>
      <webElementGuid>380b2bbd-dfe4-4a45-85f7-d1eb257cc1ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='u_0_6_BZ']</value>
      <webElementGuid>f050cd9c-084d-4464-a076-de35dadf3925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_0_o_DX']/span[3]/input</value>
      <webElementGuid>c7e84487-5432-472b-ab72-021711c06e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/input</value>
      <webElementGuid>7999a582-ed1a-4daf-817f-396cdb4c9364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'sex' and @id = 'u_0_6_BZ']</value>
      <webElementGuid>e6780668-eafc-42a7-be57-5fb5c761d0c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
